---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"

rules:
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-param-reassign: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: 0
  linebreak-style: 0
