export default (i18nextInstance) => {
  const body = document.querySelector('body');

  const modalDiv = document.createElement('div');
  modalDiv.classList.add('modal', 'fade');
  modalDiv.setAttribute('id', 'modal');
  modalDiv.setAttribute('tabindex', '-1');
  modalDiv.setAttribute('aria-labelledby', 'modal');
  modalDiv.setAttribute('style', 'display: none;');
  modalDiv.setAttribute('aria-hidden', 'true');
  modalDiv.setAttribute('role', 'dialog');
  const modalDialogDiv = document.createElement('div');
  modalDialogDiv.classList.add('modal-dialog');
  modalDialogDiv.setAttribute('role', 'document');
  const modalContentDiv = document.createElement('div');
  modalContentDiv.classList.add('modal-content');
  const modalHeader = document.createElement('div');
  modalHeader.classList.add('modal-header');
  const modalH5 = document.createElement('h5');
  modalH5.classList.add('modal-title');
  const modalHeaderButton = document.createElement('button');
  modalHeaderButton.classList.add('btn-close', 'close');
  modalHeaderButton.setAttribute('type', 'button');
  modalHeaderButton.setAttribute('data-bs-dismiss', 'modal');
  modalHeaderButton.setAttribute('aria-label', 'Close');
  const modalBody = document.createElement('div');
  modalBody.classList.add('modal-body', 'text-break');
  const modalFooter = document.createElement('div');
  modalFooter.classList.add('modal-footer');
  const modalFooterA = document.createElement('footerA');
  modalFooterA.classList.add('btn', 'btn-primary', 'full-article');
  modalFooterA.setAttribute('role', 'button');
  modalFooterA.setAttribute('href', '#');
  modalFooterA.setAttribute('target', '_blank');
  modalFooterA.setAttribute('rel', 'noopener noreferrer');
  modalFooterA.textContent = i18nextInstance.t('content.modal.button_read_full');
  const modalFooterButton = document.createElement('button');
  modalFooterButton.classList.add('btn', 'btn-secondary');
  modalFooterButton.setAttribute('type', 'button');
  modalFooterButton.setAttribute('data-bs-dismiss', 'modal');
  modalFooterButton.textContent = i18nextInstance.t('content.modal.button_close');

  const main = document.createElement('main');
  main.classList.add('flex-grow-1');
  const section = document.createElement('section');
  section.classList.add('container-fluid', 'bg-dark', 'p-5');
  const element = document.createElement('div');
  element.classList.add('row');
  const divForm = document.createElement('div');
  divForm.classList.add('col-md-10', 'col-lg-8', 'mx-auto', 'text-white');
  const h1 = document.createElement('h1');
  h1.classList.add('display-3', 'mb-0');
  h1.textContent = i18nextInstance.t('content.body.name');
  const p1 = document.createElement('p');
  p1.classList.add('lead');
  p1.textContent = i18nextInstance.t('content.body.nameNotice');
  const form = document.createElement('form');
  form.classList.add('rss-form', 'text-body');
  form.setAttribute('action', '');
  const divRow = document.createElement('div');
  divRow.classList.add('row');
  const divCol = document.createElement('div');
  divCol.classList.add('col');
  const divFloating = document.createElement('div');
  divFloating.classList.add('form-floating');
  const input = document.createElement('input');
  input.classList.add('form-control', 'w-100');
  input.setAttribute('id', 'url-input');
  input.setAttribute('autofocus', '');
  input.setAttribute('required', '');
  input.setAttribute('name', 'url');
  input.setAttribute('aria-label', 'url');
  input.setAttribute('placeholder', 'ссылка RSS');
  input.setAttribute('autocomplete', 'off');
  const label = document.createElement('label');
  label.setAttribute('for', 'url-input');
  label.textContent = i18nextInstance.t('content.body.lable');
  const divColAuto = document.createElement('div');
  divColAuto.classList.add('col-auto');
  const inputSubmit = document.createElement('button');
  inputSubmit.setAttribute('type', 'submit');
  inputSubmit.textContent = i18nextInstance.t('content.body.submitButtonName');
  inputSubmit.classList.add('h-100', 'btn', 'btn-lg', 'btn-primary', 'px-sm-5');
  const p2 = document.createElement('p');
  p2.classList.add('mt-2', 'mb-0', 'text-secondary');
  p2.textContent = i18nextInstance.t('content.body.example');
  const p3 = document.createElement('p');
  p3.classList.add('feedback', 'm-0', 'position-absolute', 'small', 'text-danger');

  const section2 = document.createElement('section');
  section2.classList.add('container-fluid', 'container-xxl', 'p-5');
  const divRow2 = document.createElement('div');
  divRow2.classList.add('row');
  const divPosts = document.createElement('div');
  divPosts.classList.add('col-md-10', 'col-lg-8', 'order-1', 'mx-auto', 'posts');
  const divFeeds = document.createElement('div');
  divFeeds.classList.add('col-md-10', 'col-lg-4', 'mx-auto', 'order-0', 'order-lg-1', 'feeds');

  const footer = document.createElement('footer');
  footer.classList.add('footer', 'border-top', 'py-3', 'mt-5', 'bg-light');
  const footerDiv = document.createElement('div');
  footerDiv.classList.add('container-xl');
  const footerDivContent = document.createElement('div');
  footerDivContent.classList.add('text-center');
  footerDivContent.textContent = i18nextInstance.t('content.footer.project_text');
  const footerA = document.createElement('a');
  footerA.setAttribute('href', i18nextInstance.t('content.footer.project_link'));
  footerA.setAttribute('target', '_blank');
  footerA.textContent = i18nextInstance.t('content.footer.project_creator');

  body.classList.add('d-flex', 'flex-column', 'min-vh-100');
  modalHeader.append(modalH5, modalHeaderButton);
  modalFooter.append(modalFooterA, modalFooterButton);
  modalContentDiv.append(modalHeader, modalBody, modalFooter);
  modalDialogDiv.append(modalContentDiv);
  modalDiv.append(modalDialogDiv);
  footerDivContent.append(footerA);
  footerDiv.append(footerDivContent);
  footer.append(footerDiv);
  divColAuto.append(inputSubmit);
  divFloating.append(input, label);
  divCol.append(divFloating);
  divRow.append(divCol, divColAuto);
  form.append(divRow);
  divForm.append(h1, p1, form, p2, p3);
  element.append(divForm);
  section.append(element);
  divRow2.append(divPosts, divFeeds);
  section2.append(divRow2);
  main.append(section, section2);
  document.body.append(modalDiv, main, footer);
};
